# Generated by Django 5.1.5 on 2025-03-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='list_of_accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=10, null=True)),
                ('quantity_cat_point', models.IntegerField(max_length=1000000, null=True)),
            ],
        ),
    ]
